"""updated News model: added nullable=true to thumbnail_path

Revision ID: 1234262421e4
Revises: b3ed6f82743c
Create Date: 2026-01-12 02:00:54.608431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1234262421e4'
down_revision: Union[str, Sequence[str], None] = 'b3ed6f82743c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
