"""Created model CRASC

Revision ID: 14ba0cb3e838
Revises: e9a350dcd679
Create Date: 2025-12-28 12:23:46.398791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ba0cb3e838'
down_revision: Union[str, Sequence[str], None] = 'e9a350dcd679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crascregion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crascregion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crascregion_name'), ['name'], unique=False)

    op.create_table('osctype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osctype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osctype_name'), ['name'], unique=True)

    op.create_table('osc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['crascregion.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['osctype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osc_name'), ['name'], unique=True)

    op.create_table('newsarticles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('preview_text', sa.String(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('osc_id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['osc_id'], ['osc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsarticles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsarticles_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsarticles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsarticles_id'))

    op.drop_table('newsarticles')
    with op.batch_alter_table('osc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osc_name'))

    op.drop_table('osc')
    with op.batch_alter_table('osctype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osctype_name'))

    op.drop_table('osctype')
    with op.batch_alter_table('crascregion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crascregion_name'))

    op.drop_table('crascregion')
    # ### end Alembic commands ###
