"""Updated model CRASC added oscs field to CrascRegion table

Revision ID: 3b8d84d16236
Revises: 928e0143ffd4
Create Date: 2025-12-28 15:58:20.018027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8d84d16236'
down_revision: Union[str, Sequence[str], None] = '928e0143ffd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
