"""Updated OscType table changed field groups to oscs

Revision ID: 4500803cd68e
Revises: 7a02bc97aaec
Create Date: 2025-12-30 09:07:20.003409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4500803cd68e'
down_revision: Union[str, Sequence[str], None] = '7a02bc97aaec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
