"""create news table

Revision ID: 58b5e0489586
Revises: 3d10723877d5
Create Date: 2026-01-11 13:58:54.155604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b5e0489586'
down_revision: Union[str, Sequence[str], None] = '3d10723877d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('osc_id', sa.Integer(), nullable=True),
    sa.Column('crasc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crasc_id'], ['crascregion.id'], ),
    sa.ForeignKeyConstraint(['osc_id'], ['osc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_id'))

    op.drop_table('news')
    # ### end Alembic commands ###
