"""creation des models PTF et Projet

Revision ID: 63c2f6577a17
Revises: 1dd6b079ae1c
Create Date: 2026-01-19 15:28:17.094743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c2f6577a17'
down_revision: Union[str, Sequence[str], None] = '1dd6b079ae1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ptf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=2048), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('ptf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ptf_name'), ['name'], unique=True)

    op.create_table('projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('ptf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ptf_id'], ['ptf.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projet')
    with op.batch_alter_table('ptf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ptf_name'))

    op.drop_table('ptf')
    # ### end Alembic commands ###
