"""updated CrascRegion and Osc models to add relationships to News model

Revision ID: 660a47d6d7a5
Revises: 58b5e0489586
Create Date: 2026-01-11 14:44:54.619074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660a47d6d7a5'
down_revision: Union[str, Sequence[str], None] = '58b5e0489586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
