"""add_payment_notify_token

Revision ID: 6a4bb84ea76f
Revises: fdcfd47a1f25
Create Date: 2026-04-15 11:56:39.206227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a4bb84ea76f'
down_revision: Union[str, Sequence[str], None] = 'fdcfd47a1f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formation_inscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_notify_token', sa.String(length=500), nullable=True))
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'gratuite'::character varying"))
        batch_op.alter_column('payment_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('formations', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'gratuite'::character varying"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formations', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'gratuite'::character varying"))

    with op.batch_alter_table('formation_inscription', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'gratuite'::character varying"))
        batch_op.drop_column('payment_notify_token')

    # ### end Alembic commands ###
