"""Updated Osc.news_articles relationship

Revision ID: 7a02bc97aaec
Revises: 4c74f30560c0
Create Date: 2025-12-28 16:17:02.562145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a02bc97aaec'
down_revision: Union[str, Sequence[str], None] = '4c74f30560c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
