"""Updated model CRASC

Revision ID: 928e0143ffd4
Revises: 14ba0cb3e838
Create Date: 2025-12-28 15:50:59.166693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928e0143ffd4'
down_revision: Union[str, Sequence[str], None] = '14ba0cb3e838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crascregion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crascregion_name'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crascregion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crascregion_name'), ['name'], unique=False)

    # ### end Alembic commands ###
