"""updated News models to add default empty string to crasc_id and osc_id

Revision ID: 9561ea452d48
Revises: bccd32e74af7
Create Date: 2026-01-11 14:59:43.680746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9561ea452d48'
down_revision: Union[str, Sequence[str], None] = 'bccd32e74af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
