"""added optional field content to news model + slugify title

Revision ID: bbcdf96b115d
Revises: 1234262421e4
Create Date: 2026-01-13 09:30:51.728502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcdf96b115d'
down_revision: Union[str, Sequence[str], None] = '1234262421e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
