"""updated News models to add nullable=True to crasc_id

Revision ID: bccd32e74af7
Revises: 660a47d6d7a5
Create Date: 2026-01-11 14:56:52.129831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccd32e74af7'
down_revision: Union[str, Sequence[str], None] = '660a47d6d7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
