"""added osc_count field to CrascRegion table

Revision ID: d0b68532eb7f
Revises: ec4ce6736183
Create Date: 2026-01-07 19:25:46.483234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b68532eb7f'
down_revision: Union[str, Sequence[str], None] = 'ec4ce6736183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crascregion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osc_count', sa.Integer(), nullable=True, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crascregion', schema=None) as batch_op:
        batch_op.drop_column('osc_count')

    # ### end Alembic commands ###
