"""generer nouvelles migrations

Revision ID: d6c7fe6b329f
Revises: 
Create Date: 2026-02-06 12:35:00.064697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c7fe6b329f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offreprojet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('osc', sa.String(length=200), nullable=False),
    sa.Column('domaine', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('durée', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.String(length=100), nullable=False),
    sa.Column('objectif', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('beneficiaires', sa.TEXT(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('progression', sa.Integer(), nullable=False),
    sa.Column('resultats_attendus', sa.TEXT(), nullable=True),
    sa.Column('partenaires', sa.TEXT(), nullable=True),
    sa.Column('image_path', sa.String(length=2048), nullable=True),
    sa.Column('date_publication', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('offreprojet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offreprojet_id'), ['id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=True)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('trainer', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('current_participants', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_full', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=2048), nullable=True),
    sa.Column('registration_link', sa.String(length=500), nullable=True),
    sa.Column('materials_link', sa.String(length=500), nullable=True),
    sa.Column('crasc_id', sa.Integer(), nullable=True),
    sa.Column('osc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crasc_id'], ['crasc.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['osc_id'], ['osc.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formations_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_formations_title'), ['title'], unique=True)

    op.create_table('news_tags',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('news_id', 'tag_id')
    )
    with op.batch_alter_table('documentation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('documentation_title_key'), type_='unique')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('missions', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('benefits', sa.TEXT(), nullable=True))

    with op.batch_alter_table('osc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ville', sa.String(length=200), nullable=True))

    with op.batch_alter_table('ptf', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ptf', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('osc', schema=None) as batch_op:
        batch_op.drop_column('ville')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('benefits')
        batch_op.drop_column('requirements')
        batch_op.drop_column('missions')

    with op.batch_alter_table('documentation', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('documentation_title_key'), ['title'], postgresql_nulls_not_distinct=False)

    op.drop_table('news_tags')
    with op.batch_alter_table('formations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formations_title'))
        batch_op.drop_index(batch_op.f('ix_formations_slug'))

    op.drop_table('formations')
    op.drop_table('hero')
    op.drop_table('team')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('offreprojet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offreprojet_id'))

    op.drop_table('offreprojet')
    # ### end Alembic commands ###
