"""added order field to CrascRegion table

Revision ID: ec4ce6736183
Revises: d59a93b96a01
Create Date: 2026-01-06 22:28:49.199871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4ce6736183'
down_revision: Union[str, Sequence[str], None] = 'd59a93b96a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crascregion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crascregion', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
