"""New init migration

Revision ID: f4220c83d0ac
Revises: 
Create Date: 2026-02-06 16:15:47.092240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4220c83d0ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crasc',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('osc_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('employer', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('missions', sa.TEXT(), nullable=True),
    sa.Column('requirements', sa.TEXT(), nullable=True),
    sa.Column('benefits', sa.TEXT(), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)

    op.create_table('keystats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('offreprojet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('osc', sa.String(length=200), nullable=False),
    sa.Column('domaine', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('durée', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.String(length=100), nullable=False),
    sa.Column('objectif', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('beneficiaires', sa.TEXT(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('progression', sa.Integer(), nullable=False),
    sa.Column('resultats_attendus', sa.TEXT(), nullable=True),
    sa.Column('partenaires', sa.TEXT(), nullable=True),
    sa.Column('image_path', sa.String(length=2048), nullable=True),
    sa.Column('date_publication', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('offreprojet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offreprojet_id'), ['id'], unique=False)

    op.create_table('osctype',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('osctype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osctype_name'), ['name'], unique=True)

    op.create_table('ptf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('mission', sa.TEXT(), nullable=True),
    sa.Column('vision', sa.TEXT(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=2048), nullable=True),
    sa.Column('cover_path', sa.String(length=2048), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('date_creation', sa.String(length=50), nullable=True),
    sa.Column('domaines', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('ptf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ptf_name'), ['name'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=True)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('osc',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=2048), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('crasc_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('ville', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crasc_id'], ['crasc.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['osctype.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('osc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osc_name'), ['name'], unique=True)

    op.create_table('projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('ptf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ptf_id'], ['ptf.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('region',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('crasc_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crasc_id'], ['crasc.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('documentation',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=2048), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=2048), nullable=True),
    sa.Column('crasc_id', sa.Integer(), nullable=True),
    sa.Column('osc_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crasc_id'], ['crasc.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['osc_id'], ['osc.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('documentation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentation_title'), ['title'], unique=True)

    op.create_table('formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('trainer', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('current_participants', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_full', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=2048), nullable=True),
    sa.Column('registration_link', sa.String(length=500), nullable=True),
    sa.Column('materials_link', sa.String(length=500), nullable=True),
    sa.Column('crasc_id', sa.Integer(), nullable=True),
    sa.Column('osc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crasc_id'], ['crasc.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['osc_id'], ['osc.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formations_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_formations_title'), ['title'], unique=True)

    op.create_table('news',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=2048), nullable=True),
    sa.Column('osc_id', sa.Integer(), nullable=True),
    sa.Column('crasc_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crasc_id'], ['crasc.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['osc_id'], ['osc.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_title'), ['title'], unique=True)

    op.create_table('news_tags',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('news_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_tags')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_title'))

    op.drop_table('news')
    with op.batch_alter_table('formations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formations_title'))
        batch_op.drop_index(batch_op.f('ix_formations_slug'))

    op.drop_table('formations')
    with op.batch_alter_table('documentation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentation_title'))

    op.drop_table('documentation')
    op.drop_table('region')
    op.drop_table('projet')
    with op.batch_alter_table('osc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osc_name'))

    op.drop_table('osc')
    op.drop_table('hero')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('team')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('ptf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ptf_name'))

    op.drop_table('ptf')
    with op.batch_alter_table('osctype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osctype_name'))

    op.drop_table('osctype')
    with op.batch_alter_table('offreprojet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offreprojet_id'))

    op.drop_table('offreprojet')
    op.drop_table('keystats')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_id'))

    op.drop_table('jobs')
    op.drop_table('crasc')
    # ### end Alembic commands ###
